### ISSUE TITLE
Why not use BERT Fine-Tune directly?

### ISSUE THREAD

**Issue by xixy** [aakanksha19/ODETTE#3]
Hi, I noticed that you only use BERT's contextual representation as input features for Bi-LSTM. Why didn't you use BERT fine-tune directly? Would you explain the motivation behind your technical design?

Thank you.

**Comment by aakanksha19** [comment]
Hi! Our base model (BERT representations fed to BiLSTM) is a reimplementation of the model architecture proposed in the LitBank paper: https://people.ischool.berkeley.edu/~dbamman/pubs/pdf/acl2019_literary_events.pdf. Because our goal was to study generalizability and domain adaptation rather than improving in-domain performance, we took the SOTA model on LitBank at the time and used the same architecture. With fine-tuning BERT instead of using it as a feature extractor, we were also worried about the potential for overfitting (since these datasets are on the smaller side) and that fine-tuning might tune BERT to the domain it was trained on, which might affect OOD performance.

Hope this helps!

**Comment by xixy** [comment]
Hi, I post the BERT Fine-tuning result as follows (BERT_BASE used, **without domain adaptation**):
`From Timebank To Litbank
In Domain: test_Precision: 0.9993823347745522 test_Recall:0.9987654320987654 test_F1:0.9990737882062365
Out-Of-Domain: test_Precision: 0.3158085569253082 test_Recall:0.8049907578558225 test_F1:0.4536458333333333
`

`From Litbank To Timebank
In Domain: test_Precision: 0.9238991021804189 test_Recall:0.9986136783733827 test_F1:0.9598045747279592
Out-Of-Domain: test_Precision: 0.9200710479573713 test_Recall:0.3197530864197531 test_F1:0.47457627118644063`

The In-domain performance is surprisingly high (I carefully checked the code and train/de/test split, which is correct.).
